# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: station.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'station.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstation.proto\x12\x07station\"E\n\x07Station\x12\x12\n\nstation_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03lat\x18\x03 \x01(\x01\x12\x0b\n\x03lon\x18\x04 \x01(\x01\"\x14\n\x12GetStationsRequest\"9\n\x13GetStationsResponse\x12\"\n\x08stations\x18\x01 \x03(\x0b\x32\x10.station.Station2Z\n\x0eStationService\x12H\n\x0bGetStations\x12\x1b.station.GetStationsRequest\x1a\x1c.station.GetStationsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'station_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATION']._serialized_start=26
  _globals['_STATION']._serialized_end=95
  _globals['_GETSTATIONSREQUEST']._serialized_start=97
  _globals['_GETSTATIONSREQUEST']._serialized_end=117
  _globals['_GETSTATIONSRESPONSE']._serialized_start=119
  _globals['_GETSTATIONSRESPONSE']._serialized_end=176
  _globals['_STATIONSERVICE']._serialized_start=178
  _globals['_STATIONSERVICE']._serialized_end=268
# @@protoc_insertion_point(module_scope)
