# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trip.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'trip.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntrip.proto\x12\x04trip\"7\n\x10StartTripRequest\x12\x10\n\x08rider_id\x18\x01 \x01(\t\x12\x11\n\tdriver_id\x18\x02 \x01(\t\"1\n\x11StartTripResponse\x12\x0f\n\x07trip_id\x18\x01 \x01(\t\x12\x0b\n\x03otp\x18\x02 \x01(\t\"-\n\rPickUpRequest\x12\x0f\n\x07trip_id\x18\x01 \x01(\t\x12\x0b\n\x03otp\x18\x02 \x01(\t\"2\n\x0ePickUpResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"!\n\x0e\x44ropOffRequest\x12\x0f\n\x07trip_id\x18\x01 \x01(\t\"3\n\x0f\x44ropOffResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xb8\x01\n\x0bTripService\x12<\n\tStartTrip\x12\x16.trip.StartTripRequest\x1a\x17.trip.StartTripResponse\x12\x33\n\x06PickUp\x12\x13.trip.PickUpRequest\x1a\x14.trip.PickUpResponse\x12\x36\n\x07\x44ropOff\x12\x14.trip.DropOffRequest\x1a\x15.trip.DropOffResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trip_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STARTTRIPREQUEST']._serialized_start=20
  _globals['_STARTTRIPREQUEST']._serialized_end=75
  _globals['_STARTTRIPRESPONSE']._serialized_start=77
  _globals['_STARTTRIPRESPONSE']._serialized_end=126
  _globals['_PICKUPREQUEST']._serialized_start=128
  _globals['_PICKUPREQUEST']._serialized_end=173
  _globals['_PICKUPRESPONSE']._serialized_start=175
  _globals['_PICKUPRESPONSE']._serialized_end=225
  _globals['_DROPOFFREQUEST']._serialized_start=227
  _globals['_DROPOFFREQUEST']._serialized_end=260
  _globals['_DROPOFFRESPONSE']._serialized_start=262
  _globals['_DROPOFFRESPONSE']._serialized_end=313
  _globals['_TRIPSERVICE']._serialized_start=316
  _globals['_TRIPSERVICE']._serialized_end=500
# @@protoc_insertion_point(module_scope)
