# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import trip_pb2 as trip__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in trip_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TripServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartTrip = channel.unary_unary(
                '/trip.TripService/StartTrip',
                request_serializer=trip__pb2.StartTripRequest.SerializeToString,
                response_deserializer=trip__pb2.StartTripResponse.FromString,
                _registered_method=True)
        self.PickUp = channel.unary_unary(
                '/trip.TripService/PickUp',
                request_serializer=trip__pb2.PickUpRequest.SerializeToString,
                response_deserializer=trip__pb2.PickUpResponse.FromString,
                _registered_method=True)
        self.DropOff = channel.unary_unary(
                '/trip.TripService/DropOff',
                request_serializer=trip__pb2.DropOffRequest.SerializeToString,
                response_deserializer=trip__pb2.DropOffResponse.FromString,
                _registered_method=True)


class TripServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartTrip(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PickUp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropOff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TripServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartTrip': grpc.unary_unary_rpc_method_handler(
                    servicer.StartTrip,
                    request_deserializer=trip__pb2.StartTripRequest.FromString,
                    response_serializer=trip__pb2.StartTripResponse.SerializeToString,
            ),
            'PickUp': grpc.unary_unary_rpc_method_handler(
                    servicer.PickUp,
                    request_deserializer=trip__pb2.PickUpRequest.FromString,
                    response_serializer=trip__pb2.PickUpResponse.SerializeToString,
            ),
            'DropOff': grpc.unary_unary_rpc_method_handler(
                    servicer.DropOff,
                    request_deserializer=trip__pb2.DropOffRequest.FromString,
                    response_serializer=trip__pb2.DropOffResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trip.TripService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('trip.TripService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TripService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartTrip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trip.TripService/StartTrip',
            trip__pb2.StartTripRequest.SerializeToString,
            trip__pb2.StartTripResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PickUp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trip.TripService/PickUp',
            trip__pb2.PickUpRequest.SerializeToString,
            trip__pb2.PickUpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DropOff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trip.TripService/DropOff',
            trip__pb2.DropOffRequest.SerializeToString,
            trip__pb2.DropOffResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
