# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: matching.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'matching.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ematching.proto\x12\x08matching\x1a\x1bgoogle/protobuf/empty.proto\"=\n\x0e\x44riverPosition\x12\x11\n\tdriver_id\x18\x01 \x01(\t\x12\x0b\n\x03lat\x18\x02 \x01(\x01\x12\x0b\n\x03lon\x18\x03 \x01(\x01\" \n\x0cMatchRequest\x12\x10\n\x08rider_id\x18\x01 \x01(\t\"{\n\rMatchResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x11\n\tdriver_id\x18\x02 \x01(\t\x12\x10\n\x08rider_id\x18\x03 \x01(\t\x12\x0b\n\x03otp\x18\x04 \x01(\t\x12\x13\n\x0b\x64river_name\x18\x05 \x01(\t\x12\x14\n\x0c\x64river_phone\x18\x06 \x01(\t2\x9e\x01\n\x0fMatchingService\x12J\n\x16\x45valuateDriverPosition\x12\x18.matching.DriverPosition\x1a\x16.google.protobuf.Empty\x12?\n\x0cRequestMatch\x12\x16.matching.MatchRequest\x1a\x17.matching.MatchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'matching_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DRIVERPOSITION']._serialized_start=57
  _globals['_DRIVERPOSITION']._serialized_end=118
  _globals['_MATCHREQUEST']._serialized_start=120
  _globals['_MATCHREQUEST']._serialized_end=152
  _globals['_MATCHRESPONSE']._serialized_start=154
  _globals['_MATCHRESPONSE']._serialized_end=277
  _globals['_MATCHINGSERVICE']._serialized_start=280
  _globals['_MATCHINGSERVICE']._serialized_end=438
# @@protoc_insertion_point(module_scope)
