# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: driver.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'driver.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64river.proto\x12\x06\x64river\"?\n\rDriverDetails\x12\x11\n\tdriver_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05phone\x18\x03 \x01(\t\"<\n\x12SendDriversRequest\x12&\n\x07\x64rivers\x18\x01 \x03(\x0b\x32\x15.driver.DriverDetails\"5\n\x13SendDriversResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\">\n\x19UpdateDriverStatusRequest\x12\x11\n\tdriver_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"R\n\x18SetDriverPositionRequest\x12\x11\n\tdriver_id\x18\x01 \x01(\t\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x11\n\tlongitude\x18\x03 \x01(\x01\",\n\x19SetDriverPositionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"-\n\x1aUpdateDriverStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x98\x02\n\rDriverService\x12[\n\x12UpdateDriverStatus\x12!.driver.UpdateDriverStatusRequest\x1a\".driver.UpdateDriverStatusResponse\x12\x46\n\x0bSendDrivers\x12\x1a.driver.SendDriversRequest\x1a\x1b.driver.SendDriversResponse\x12\x62\n\x1bSetAndForwardDriverPosition\x12 .driver.SetDriverPositionRequest\x1a!.driver.SetDriverPositionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'driver_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DRIVERDETAILS']._serialized_start=24
  _globals['_DRIVERDETAILS']._serialized_end=87
  _globals['_SENDDRIVERSREQUEST']._serialized_start=89
  _globals['_SENDDRIVERSREQUEST']._serialized_end=149
  _globals['_SENDDRIVERSRESPONSE']._serialized_start=151
  _globals['_SENDDRIVERSRESPONSE']._serialized_end=204
  _globals['_UPDATEDRIVERSTATUSREQUEST']._serialized_start=206
  _globals['_UPDATEDRIVERSTATUSREQUEST']._serialized_end=268
  _globals['_SETDRIVERPOSITIONREQUEST']._serialized_start=270
  _globals['_SETDRIVERPOSITIONREQUEST']._serialized_end=352
  _globals['_SETDRIVERPOSITIONRESPONSE']._serialized_start=354
  _globals['_SETDRIVERPOSITIONRESPONSE']._serialized_end=398
  _globals['_UPDATEDRIVERSTATUSRESPONSE']._serialized_start=400
  _globals['_UPDATEDRIVERSTATUSRESPONSE']._serialized_end=445
  _globals['_DRIVERSERVICE']._serialized_start=448
  _globals['_DRIVERSERVICE']._serialized_end=728
# @@protoc_insertion_point(module_scope)
