# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import driver_pb2 as driver__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in driver_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DriverServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateDriverStatus = channel.unary_unary(
                '/driver.DriverService/UpdateDriverStatus',
                request_serializer=driver__pb2.UpdateDriverStatusRequest.SerializeToString,
                response_deserializer=driver__pb2.UpdateDriverStatusResponse.FromString,
                _registered_method=True)
        self.SendDrivers = channel.unary_unary(
                '/driver.DriverService/SendDrivers',
                request_serializer=driver__pb2.SendDriversRequest.SerializeToString,
                response_deserializer=driver__pb2.SendDriversResponse.FromString,
                _registered_method=True)
        self.SetAndForwardDriverPosition = channel.unary_unary(
                '/driver.DriverService/SetAndForwardDriverPosition',
                request_serializer=driver__pb2.SetDriverPositionRequest.SerializeToString,
                response_deserializer=driver__pb2.SetDriverPositionResponse.FromString,
                _registered_method=True)


class DriverServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateDriverStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendDrivers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAndForwardDriverPosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DriverServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateDriverStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDriverStatus,
                    request_deserializer=driver__pb2.UpdateDriverStatusRequest.FromString,
                    response_serializer=driver__pb2.UpdateDriverStatusResponse.SerializeToString,
            ),
            'SendDrivers': grpc.unary_unary_rpc_method_handler(
                    servicer.SendDrivers,
                    request_deserializer=driver__pb2.SendDriversRequest.FromString,
                    response_serializer=driver__pb2.SendDriversResponse.SerializeToString,
            ),
            'SetAndForwardDriverPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAndForwardDriverPosition,
                    request_deserializer=driver__pb2.SetDriverPositionRequest.FromString,
                    response_serializer=driver__pb2.SetDriverPositionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'driver.DriverService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('driver.DriverService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DriverService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateDriverStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/driver.DriverService/UpdateDriverStatus',
            driver__pb2.UpdateDriverStatusRequest.SerializeToString,
            driver__pb2.UpdateDriverStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendDrivers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/driver.DriverService/SendDrivers',
            driver__pb2.SendDriversRequest.SerializeToString,
            driver__pb2.SendDriversResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAndForwardDriverPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/driver.DriverService/SetAndForwardDriverPosition',
            driver__pb2.SetDriverPositionRequest.SerializeToString,
            driver__pb2.SetDriverPositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
