# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import rider_pb2 as rider__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rider_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RiderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterRider = channel.unary_unary(
                '/rider.RiderService/RegisterRider',
                request_serializer=rider__pb2.RegisterRiderRequest.SerializeToString,
                response_deserializer=rider__pb2.RegisterRiderResponse.FromString,
                _registered_method=True)
        self.UpdateRiderStatus = channel.unary_unary(
                '/rider.RiderService/UpdateRiderStatus',
                request_serializer=rider__pb2.UpdateRiderStatusRequest.SerializeToString,
                response_deserializer=rider__pb2.UpdateRiderStatusResponse.FromString,
                _registered_method=True)
        self.GetRiderInfo = channel.unary_unary(
                '/rider.RiderService/GetRiderInfo',
                request_serializer=rider__pb2.GetRiderInfoRequest.SerializeToString,
                response_deserializer=rider__pb2.GetRiderInfoResponse.FromString,
                _registered_method=True)


class RiderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterRider(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRiderStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRiderInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RiderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterRider': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterRider,
                    request_deserializer=rider__pb2.RegisterRiderRequest.FromString,
                    response_serializer=rider__pb2.RegisterRiderResponse.SerializeToString,
            ),
            'UpdateRiderStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRiderStatus,
                    request_deserializer=rider__pb2.UpdateRiderStatusRequest.FromString,
                    response_serializer=rider__pb2.UpdateRiderStatusResponse.SerializeToString,
            ),
            'GetRiderInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRiderInfo,
                    request_deserializer=rider__pb2.GetRiderInfoRequest.FromString,
                    response_serializer=rider__pb2.GetRiderInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rider.RiderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rider.RiderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RiderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterRider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rider.RiderService/RegisterRider',
            rider__pb2.RegisterRiderRequest.SerializeToString,
            rider__pb2.RegisterRiderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRiderStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rider.RiderService/UpdateRiderStatus',
            rider__pb2.UpdateRiderStatusRequest.SerializeToString,
            rider__pb2.UpdateRiderStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRiderInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rider.RiderService/GetRiderInfo',
            rider__pb2.GetRiderInfoRequest.SerializeToString,
            rider__pb2.GetRiderInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
