# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notification.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'notification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12notification.proto\x12\x0cnotification\"1\n\rNotifyRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"!\n\x0eNotifyResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x64\n\x13NotificationService\x12M\n\x10SendNotification\x12\x1b.notification.NotifyRequest\x1a\x1c.notification.NotifyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTIFYREQUEST']._serialized_start=36
  _globals['_NOTIFYREQUEST']._serialized_end=85
  _globals['_NOTIFYRESPONSE']._serialized_start=87
  _globals['_NOTIFYRESPONSE']._serialized_end=120
  _globals['_NOTIFICATIONSERVICE']._serialized_start=122
  _globals['_NOTIFICATIONSERVICE']._serialized_end=222
# @@protoc_insertion_point(module_scope)
